/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectcreator.gui;

import Bussines.JatFilesManager;
import java.awt.Dimension;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Danzelord
 */
public class JATGUI extends javax.swing.JFrame {
    JFileChooser buscador;
    private final String configFile = ".jat.txt";
    JLabel[] labels= new JLabel[5];
    /**
     * Creates new form AcctTGUI
     */
    public JATGUI() {
        initComponents();
        labels[0]=recentRepository1;
        labels[1]=recentRepository2;
        labels[2]=recentRepository3;
        labels[3]=recentRepository4;
        labels[4]=recentRepository5;
        reDesignHistoryList();
        buscador= new JFileChooser();
        //buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        buscador.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        buscador.setDialogType(JFileChooser.SAVE_DIALOG);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        createNewRepository = new javax.swing.JButton();
        openExistingRepository = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        recentRepository1 = new javax.swing.JLabel();
        recentRepository2 = new javax.swing.JLabel();
        recentRepository3 = new javax.swing.JLabel();
        recentRepository4 = new javax.swing.JLabel();
        recentRepository5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JAT GUI");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.PNG"))); // NOI18N
        logo.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 776, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        createNewRepository.setText("Create New Repository");
        createNewRepository.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewRepositoryActionPerformed(evt);
            }
        });

        openExistingRepository.setText("Open Existing Repository");
        openExistingRepository.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openExistingRepositoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Open Recent Repository");

        recentRepository1.setForeground(new java.awt.Color(0, 0, 255));
        recentRepository1.setText("jLabel2");
        recentRepository1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentRepository1MouseClicked(evt);
            }
        });

        recentRepository2.setForeground(new java.awt.Color(0, 0, 255));
        recentRepository2.setText("jLabel2");
        recentRepository2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentRepository2MouseClicked(evt);
            }
        });

        recentRepository3.setForeground(new java.awt.Color(0, 0, 255));
        recentRepository3.setText("jLabel2");
        recentRepository3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentRepository3MouseClicked(evt);
            }
        });

        recentRepository4.setForeground(new java.awt.Color(0, 0, 255));
        recentRepository4.setText("jLabel2");
        recentRepository4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentRepository4MouseClicked(evt);
            }
        });

        recentRepository5.setForeground(new java.awt.Color(0, 0, 255));
        recentRepository5.setText("jLabel2");
        recentRepository5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentRepository5MouseClicked(evt);
            }
        });

        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createNewRepository, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openExistingRepository, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recentRepository2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recentRepository3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recentRepository4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recentRepository5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(recentRepository1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recentRepository1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recentRepository2))
                    .addComponent(createNewRepository, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recentRepository3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recentRepository4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recentRepository5))
                    .addComponent(openExistingRepository, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        recentRepository1.getAccessibleContext().setAccessibleName("recentRepository1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewRepositoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewRepositoryActionPerformed
        // TODO add your handling code here:
        dispose();
        ProyectCreatorGUI proyectCreatorGUI = new ProyectCreatorGUI(/*configFile*/);
        proyectCreatorGUI.setVisible(true);
    }//GEN-LAST:event_createNewRepositoryActionPerformed

    private void recentRepository1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentRepository1MouseClicked
        openRepositorySelected(recentRepository1.getText());
    }//GEN-LAST:event_recentRepository1MouseClicked

    private void openExistingRepositoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openExistingRepositoryActionPerformed
        // TODO add your handling code here:
        buscador.setDialogType(JFileChooser.OPEN_DIALOG);
        int seleccion = buscador.showOpenDialog(buscador);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File origen = buscador.getSelectedFile();
            JatFilesManager repositoryHistory= new JatFilesManager(null);
            repositoryHistory.writeNewLog(origen.getAbsolutePath());
            reDesignHistoryList();
            MultiCreatorGUI multiCreatorGUI= new MultiCreatorGUI(origen.getAbsolutePath().split(configFile)[0]);
            multiCreatorGUI.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_openExistingRepositoryActionPerformed

    private void recentRepository2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentRepository2MouseClicked
        openRepositorySelected(recentRepository2.getText());
    }//GEN-LAST:event_recentRepository2MouseClicked

    private void recentRepository3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentRepository3MouseClicked
        openRepositorySelected(recentRepository3.getText());
    }//GEN-LAST:event_recentRepository3MouseClicked

    private void recentRepository4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentRepository4MouseClicked
        openRepositorySelected(recentRepository4.getText());
    }//GEN-LAST:event_recentRepository4MouseClicked

    private void recentRepository5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentRepository5MouseClicked
        openRepositorySelected(recentRepository5.getText());
    }//GEN-LAST:event_recentRepository5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JATGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JATGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JATGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JATGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JATGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewRepository;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton openExistingRepository;
    private javax.swing.JLabel recentRepository1;
    private javax.swing.JLabel recentRepository2;
    private javax.swing.JLabel recentRepository3;
    private javax.swing.JLabel recentRepository4;
    private javax.swing.JLabel recentRepository5;
    // End of variables declaration//GEN-END:variables

    private void openRepositorySelected(String text) {
        System.out.println(text);
        MultiCreatorGUI creatorGUI= new MultiCreatorGUI(text);
        creatorGUI.setVisible(true);
        dispose();
    }

    private void reDesignHistoryList() {
        JatFilesManager repositoryHistory= new JatFilesManager(null);
        for (int i = 0; i < 5; i++) {
            labels[i].setText(repositoryHistory.readLog(repositoryHistory.getLenght()-i));
        }
    }
}
