/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectcreator.gui;

import Bussines.JatFilesManager;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Danzelord
 */
public class MultiCreatorGUI extends javax.swing.JFrame {
    JFileChooser buscador;
    private String rootPath;
    private String configFile;
    /**
     * 
     * @param path
     * @param configFile 
     */
   /* public MultiCreatorGUI(String path, String configFile) {
        initComponents();
        buscador= new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        buscador.setDialogType(JFileChooser.SAVE_DIALOG);
        this.path=path;
        this.configFile = configFile;
        //putAllSources();
        buscador.setCurrentDirectory(new File(path));
        POandDeclarationHistory declarationHistory = new POandDeclarationHistory(path, configFile);
        String story = declarationHistory.readConfigFile();
        poFactoryLocation.setText(story.split(POandDeclarationHistory.Factory_Link+":")[1].split(";")[0]);
        poLocation.setText(story.split(POandDeclarationHistory.PO_Link+":")[1].split(";")[0]);
        testsLocation.setText(story.split(POandDeclarationHistory.Test_Link+":")[1].substring(0,story.split(POandDeclarationHistory.Test_Link+":")[1].length()-1));//.split(";")[0]);
    }
*/
    public MultiCreatorGUI(String rootPath) {
        initComponents();
        buscador= new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        buscador.setDialogType(JFileChooser.SAVE_DIALOG);
        this.rootPath=rootPath;
        this.configFile = configFile;
        //putAllSources();
        buscador.setCurrentDirectory(new File(this.rootPath));
        JatFilesManager declarationHistory = new JatFilesManager(this.rootPath);
        String story = declarationHistory.readConfigFile();
        System.err.println(story+"********************************************");
        poFactoryLocation.setText(story.split(JatFilesManager.Factory_Link+":")[1].split(";")[0]);
        poLocation.setText(story.split(JatFilesManager.PO_Link+":")[1].split(";")[0]);
        testsLocation.setText(story.split(JatFilesManager.Test_Link+":")[1].substring(0,story.split(JatFilesManager.Test_Link+":")[1].length()-1));//.split(";")[0]);
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width/2)-this.getWidth()/2,(screenSize.height/2)-this.getHeight()/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poLocationLabel = new javax.swing.JLabel();
        poFactoryLocationLabel = new javax.swing.JLabel();
        testLocationLabel = new javax.swing.JLabel();
        poFactoryLocation = new javax.swing.JTextField();
        poLocation = new javax.swing.JTextField();
        testsLocation = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchButton1 = new javax.swing.JButton();
        searchButton2 = new javax.swing.JButton();
        createPO = new javax.swing.JButton();
        createTest = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        poLocationLabel.setText("Location for Page Objects");

        poFactoryLocationLabel.setText("Location for Page Object Factory");

        testLocationLabel.setText("Location for Tests");

        poLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poLocationActionPerformed(evt);
            }
        });

        testsLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testsLocationActionPerformed(evt);
            }
        });

        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchButton1.setText("search");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        searchButton2.setText("search");
        searchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton2ActionPerformed(evt);
            }
        });

        createPO.setText("Create a Page Object");
        createPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPOActionPerformed(evt);
            }
        });

        createTest.setText("Create a Test");
        createTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTestActionPerformed(evt);
            }
        });

        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poFactoryLocationLabel)
                            .addComponent(poLocationLabel)
                            .addComponent(testLocationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(poLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(poFactoryLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poFactoryLocationLabel)
                    .addComponent(poFactoryLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poLocationLabel)
                    .addComponent(poLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(testsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(testLocationLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(createPO)
                    .addComponent(createTest))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poLocationActionPerformed

    private void testsLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testsLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testsLocationActionPerformed

    private void reWriteConfigFile(){
        JatFilesManager declarationHistory = new JatFilesManager(this.rootPath);
        declarationHistory.reWriteConfigFile(poFactoryLocation.getText(), poLocation.getText(), testsLocation.getText());
    }
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        int seleccion = buscador.showSaveDialog(buscador);
        System.out.println(this.rootPath);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File origen = buscador.getSelectedFile();
            poFactoryLocation.setText(origen.getAbsolutePath());
            reWriteConfigFile();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        int seleccion = buscador.showSaveDialog(buscador);
        System.out.println(this.rootPath);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File origen = buscador.getSelectedFile();
            poLocation.setText(origen.getAbsolutePath());
            reWriteConfigFile();
        }
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void searchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton2ActionPerformed
        int seleccion = buscador.showSaveDialog(buscador);
        System.out.println(this.rootPath);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File origen = buscador.getSelectedFile();
            testsLocation.setText(origen.getAbsolutePath());
            reWriteConfigFile();
        }
    }//GEN-LAST:event_searchButton2ActionPerformed

    private void createPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPOActionPerformed
        reWriteConfigFile();
        POcreatorGUI pOcreatorUI=new POcreatorGUI(rootPath ,poLocation.getText(), poFactoryLocation.getText());
        pOcreatorUI.setVisible(true);
    }//GEN-LAST:event_createPOActionPerformed

    private void createTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTestActionPerformed
        TestCreatorGUI testCreator= new TestCreatorGUI(rootPath, testsLocation.getText());
        testCreator.setVisible(true);
    }//GEN-LAST:event_createTestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JATGUI jatgui = new JATGUI();
        jatgui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /*private void putAllSources(){
        POandDeclarationHistory declarationHistory = new POandDeclarationHistory(path);
        System.out.println(path);
        if (declarationHistory.getLenght()<2) {
            declarationHistory.writeNewLog(POandDeclarationHistory.Factory_Link, path.split(".jat")[0]+"src\\");
            declarationHistory.writeNewLog(POandDeclarationHistory.PO_Link, path.split(".jat")[0]+"src\\");
            declarationHistory.writeNewLog(POandDeclarationHistory.Test_Link, path.split(".jat")[0]+"src\\");
        }
        poFactoryLocation.setText(declarationHistory.readLog(POandDeclarationHistory.Factory_Link));
        poLocation.setText(declarationHistory.readLog(POandDeclarationHistory.PO_Link));
        testsLocation.setText(declarationHistory.readLog(POandDeclarationHistory.Test_Link));
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MultiCreatorGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPO;
    private javax.swing.JButton createTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField poFactoryLocation;
    private javax.swing.JLabel poFactoryLocationLabel;
    private javax.swing.JTextField poLocation;
    private javax.swing.JLabel poLocationLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    private javax.swing.JButton searchButton2;
    private javax.swing.JLabel testLocationLabel;
    private javax.swing.JTextField testsLocation;
    // End of variables declaration//GEN-END:variables
}
